import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { MOCK_KEYS, MOCK_SERVICES } from '@/lib/mockData';

// Provider upstream base URL mappings
const PROVIDER_BASE_URLS: Record<string, string> = {
  github: 'https://api.github.com',
  openai: 'https://api.openai.com',
  groq: 'https://api.groq.com/openai',
  stripe: 'https://api.stripe.com',
  twilio: 'https://api.twilio.com',
  openweather: 'https://api.openweathermap.org',
  weather: 'https://api.openweathermap.org',
  alphavantage: 'https://www.alphavantage.co',
};

/**
 * Extract the canonical provider type from a potentially dynamic service ID.
 * Dynamic IDs generated by AddKeyModal have the form "{providerType}-{timestamp}".
 * e.g. "groq-1748234567890" -> "groq"
 */
function resolveProviderType(serviceId: string): string {
  const known = Object.keys(PROVIDER_BASE_URLS);
  // Direct match first
  if (known.includes(serviceId)) return serviceId;
  // Strip numeric/timestamp suffix: "groq-1748234567890" -> "groq"
  const match = serviceId.match(/^([a-z]+(?:[a-z]+)?)-\d+$/);
  if (match && known.includes(match[1])) return match[1];
  // Try splitting on first dash
  const prefix = serviceId.split('-')[0];
  if (known.includes(prefix)) return prefix;
  return serviceId;
}

async function handleProxyRequest(
  req: NextRequest,
  serviceId: string,
  pathSegments: string[] = []
) {
  const startTime = performance.now();
  const rawPath = pathSegments.join('/');
  const searchParams = req.nextUrl.search; // includes query string '?foo=bar'
  
  // 1. Fetch Service metadata
  let service = await prisma.apiService.findUnique({
    where: { id: serviceId },
  }).catch(() => null);

  if (!service) {
    const fallbackSvc = MOCK_SERVICES.find((s) => s.id === serviceId);
    if (fallbackSvc) {
      service = {
        ...fallbackSvc,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    }
  }

  // 2. Fetch Active API Key from PostgreSQL
  const SEED_RAW_KEYS = new Set(MOCK_KEYS.map((mk) => mk.rawKey));
  let keyRecord = await prisma.apiKey.findFirst({
    where: { serviceId, status: 'active' },
    orderBy: { createdAt: 'desc' },
  }).catch(() => null);

  // Resolve canonical provider type (handles dynamic IDs like "groq-1748234567890")
  const providerType = resolveProviderType(serviceId);

  let rawKey = '';
  const isCustomDbKey =
    Boolean(keyRecord?.rawKey) &&
    !SEED_RAW_KEYS.has(keyRecord!.rawKey) &&
    keyRecord!.rawKey.length > 5;

  if (isCustomDbKey) {
    // User explicitly configured or added this key in the database UI
    rawKey = keyRecord!.rawKey;
  } else {
    // Fall back to environment variable if configured
    if (providerType === 'openai' && process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY.length > 20) {
      rawKey = process.env.OPENAI_API_KEY;
    } else if (providerType === 'github' && process.env.GITHUB_TOKEN && process.env.GITHUB_TOKEN.length > 10) {
      rawKey = process.env.GITHUB_TOKEN;
    } else if (providerType === 'stripe' && process.env.STRIPE_SECRET_KEY && process.env.STRIPE_SECRET_KEY.length > 10) {
      rawKey = process.env.STRIPE_SECRET_KEY;
    } else if (providerType === 'groq' && process.env.GROQ_API_KEY && process.env.GROQ_API_KEY.length > 10) {
      rawKey = process.env.GROQ_API_KEY;
    } else if ((providerType === 'openweather' || providerType === 'weather') && process.env.OPENWEATHER_API_KEY && process.env.OPENWEATHER_API_KEY.length > 10) {
      rawKey = process.env.OPENWEATHER_API_KEY;
    } else if (providerType === 'alphavantage' && process.env.ALPHAVANTAGE_API_KEY && process.env.ALPHAVANTAGE_API_KEY.length > 5) {
      rawKey = process.env.ALPHAVANTAGE_API_KEY;
    } else if (providerType === 'twilio' && process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN) {
      rawKey = `${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`;
    } else {
      rawKey = keyRecord?.rawKey || '';
    }
  }

  // Determine Upstream Base URL — prefer DB service endpointUrl for custom providers
  const baseUrl = PROVIDER_BASE_URLS[providerType] || service?.endpointUrl || 'https://api.github.com';
  let targetUrl = `${baseUrl.replace(/\/+$/, '')}/${rawPath.replace(/^\/+/, '')}${searchParams}`;

  // 3. Prepare headers & Provider-specific Authorization injection
  const forwardHeaders = new Headers();

  // Forward safe client headers only
  const passThroughHeaders = ['content-type', 'accept', 'accept-language'];
  passThroughHeaders.forEach((h) => {
    const val = req.headers.get(h);
    if (val) forwardHeaders.set(h, val);
  });

  forwardHeaders.set('User-Agent', 'KeyVault-API-Gateway/1.0');

  // Only block the exact seed placeholder values from mockData.ts
  const isSeedPlaceholder = SEED_RAW_KEYS.has(rawKey);

  const isRealKey =
    Boolean(rawKey) &&
    !isSeedPlaceholder &&
    !rawKey.toLowerCase().includes('mock') &&
    !rawKey.toLowerCase().includes('demo') &&
    !rawKey.toLowerCase().includes('placeholder') &&
    rawKey.length > 10;

  console.log('[KeyVault Gateway] Request:', {
    serviceId,
    rawPath,
    targetUrl,
    keyPrefix: rawKey.slice(0, 8) + '...',
    isRealKey,
    quota: service ? `${service.used}/${service.limit}` : 'untracked',
  });

  // 3.5. Gateway Quota Policy Enforcement
  // If the internal service quota has reached or exceeded 100%, block with real HTTP 429
  if (service && service.limit > 0 && service.used >= service.limit) {
    const latencyMs = Math.round(performance.now() - startTime);

    // Record the blocked 429 attempt in PostgreSQL
    try {
      await prisma.usageLog.create({
        data: {
          serviceId,
          serviceName: service.name,
          endpoint: `/${rawPath}${searchParams ? searchParams.slice(0, 30) : ''}`,
          status: 429,
          responseTime: `${latencyMs}ms`,
          payloadSize: '0.4 KB',
          timestamp: new Date().toLocaleTimeString(),
        },
      });
    } catch (logErr) {
      console.warn('Logging 429 notice:', logErr);
    }

    const responseHeaders = new Headers();
    responseHeaders.set('Content-Type', 'application/json');
    responseHeaders.set('X-KeyVault-Gateway', 'true');
    responseHeaders.set('X-KeyVault-Blocked', 'Quota-Exceeded');
    responseHeaders.set('X-KeyVault-Latency', `${latencyMs}ms`);
    responseHeaders.set('X-KeyVault-Service', serviceId);

    return new NextResponse(
      JSON.stringify({
        error: 'HTTP 429 Too Many Requests (KeyVault Gateway Enforced)',
        service: service.name,
        serviceId: service.id,
        currentUsage: service.used,
        quotaLimit: service.limit,
        status: 429,
        message: `KeyVault Gateway Policy: Quota limit for ${service.name} is 100% exhausted (${service.used}/${service.limit}). Request rejected by KeyVault Gateway to prevent account overspend.`,
        recommendation: 'Refill quota or upgrade tier in KeyVault to resume forwarding.',
      }, null, 2),
      {
        status: 429,
        headers: responseHeaders,
      }
    );
  }

  if (isRealKey) {
    if (providerType === 'github') {
      forwardHeaders.set('Authorization', `Bearer ${rawKey}`);
      forwardHeaders.set('Accept', 'application/vnd.github.v3+json');
      forwardHeaders.set('X-GitHub-Api-Version', '2022-11-28');
    } else if (providerType === 'openai' || providerType === 'groq') {
      forwardHeaders.set('Authorization', `Bearer ${rawKey}`);
      forwardHeaders.set('Content-Type', 'application/json');
    } else if (providerType === 'stripe') {
      forwardHeaders.set('Authorization', `Bearer ${rawKey}`);
    } else if (providerType === 'twilio') {
      // Twilio Basic Auth: base64(AccountSID:AuthToken)
      const encoded = Buffer.from(rawKey).toString('base64');
      forwardHeaders.set('Authorization', `Basic ${encoded}`);
    } else if (providerType === 'alphavantage') {
      const joinChar = targetUrl.includes('?') ? '&' : '?';
      targetUrl = `${targetUrl}${joinChar}apikey=${rawKey}`;
    } else if (providerType === 'openweather' || providerType === 'weather') {
      const joinChar = targetUrl.includes('?') ? '&' : '?';
      targetUrl = `${targetUrl}${joinChar}appid=${rawKey}`;
    } else {
      forwardHeaders.set('Authorization', `Bearer ${rawKey}`);
    }
  } else if (providerType === 'github') {
    // Unauthenticated GitHub: still set Accept header (60 req/hr limit applies)
    forwardHeaders.set('Accept', 'application/vnd.github.v3+json');
    forwardHeaders.set('X-GitHub-Api-Version', '2022-11-28');
  }

  // 4. Execute Upstream Request
  let upstreamRes: Response;
  let responseBody: string | ArrayBuffer = '';
  let contentType = 'application/json';

  try {
    const hasBody = req.method !== 'GET' && req.method !== 'HEAD';
    const bodyContent = hasBody ? await req.arrayBuffer() : undefined;

    upstreamRes = await fetch(targetUrl, {
      method: req.method,
      headers: forwardHeaders,
      body: bodyContent,
    });

    contentType = upstreamRes.headers.get('content-type') || 'application/json';
    if (contentType.includes('application/json') || contentType.includes('text/')) {
      responseBody = await upstreamRes.text();
    } else {
      responseBody = await upstreamRes.arrayBuffer();
    }
  } catch (err: any) {
    const latencyMs = Math.round(performance.now() - startTime);
    return NextResponse.json(
      {
        error: 'KeyVault Gateway Failed to connect to Upstream API',
        targetUrl,
        latency: `${latencyMs}ms`,
        details: err?.message || String(err),
      },
      { status: 502 }
    );
  }

  const latencyMs = Math.round(performance.now() - startTime);

  // 5. Extract Upstream Telemetry & Rate Limit Headers
  const rateLimitRemaining =
    upstreamRes.headers.get('x-ratelimit-remaining') ||
    upstreamRes.headers.get('x-ratelimit-remaining-requests') ||
    upstreamRes.headers.get('ratelimit-remaining');

  const rateLimitLimit =
    upstreamRes.headers.get('x-ratelimit-limit') ||
    upstreamRes.headers.get('x-ratelimit-limit-requests') ||
    upstreamRes.headers.get('ratelimit-limit');

  const rateLimitReset =
    upstreamRes.headers.get('x-ratelimit-reset') ||
    upstreamRes.headers.get('x-ratelimit-reset-requests');

  // Compute Payload Size
  const byteLength =
    typeof responseBody === 'string'
      ? Buffer.byteLength(responseBody, 'utf8')
      : responseBody.byteLength;
  const payloadSizeStr = `${(byteLength / 1024).toFixed(1)} KB`;

  // 6. Record Real Usage Log in PostgreSQL
  try {
    await prisma.usageLog.create({
      data: {
        serviceId,
        serviceName: service?.name || serviceId,
        endpoint: `/${rawPath}${searchParams ? searchParams.slice(0, 30) : ''}`,
        status: upstreamRes.status,
        responseTime: `${latencyMs}ms`,
        payloadSize: payloadSizeStr,
        timestamp: new Date().toLocaleTimeString(),
      },
    });
  } catch (logErr) {
    console.warn('Gateway log persistence notice:', logErr);
  }

  // 7. Update Service Live Quota & Latency in PostgreSQL
  try {
    const hasUpstreamQuotaHeaders = Boolean(rateLimitRemaining && rateLimitLimit);
    let explicitNewUsed: number | undefined = undefined;
    if (hasUpstreamQuotaHeaders) {
      const remainingNum = parseInt(rateLimitRemaining!, 10);
      const limitNum = parseInt(rateLimitLimit!, 10);
      if (!isNaN(remainingNum) && !isNaN(limitNum) && limitNum > 0) {
        explicitNewUsed = Math.max(0, limitNum - remainingNum);
      }
    }

    let resetTimeFormatted = service?.resetTime || '24h';
    if (rateLimitReset) {
      const resetEpoch = parseInt(rateLimitReset, 10);
      if (!isNaN(resetEpoch) && resetEpoch > 1000000000) {
        const resetDate = new Date(resetEpoch * 1000);
        resetTimeFormatted = resetDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      } else {
        resetTimeFormatted = rateLimitReset;
      }
    }

    const statusStr = upstreamRes.status === 429 ? 'critical' : upstreamRes.status >= 500 ? 'warning' : 'healthy';
    const statusColorStr = upstreamRes.status === 429 ? 'red' : upstreamRes.status >= 500 ? 'yellow' : 'green';

    if (service?.id) {
      await prisma.apiService.update({
        where: { id: service.id },
        data: {
          used: explicitNewUsed !== undefined ? explicitNewUsed : { increment: 1 },
          latencyMs,
          status: statusStr,
          statusColor: statusColorStr,
          resetTime: resetTimeFormatted,
        },
      });
    }
  } catch (updateErr) {
    console.warn('Gateway service sync notice:', updateErr);
  }

  // 8. Return Response with Gateway Telemetry Headers
  const responseHeaders = new Headers();
  upstreamRes.headers.forEach((value, key) => {
    // Avoid hop-by-hop headers
    if (!['transfer-encoding', 'connection', 'content-encoding'].includes(key.toLowerCase())) {
      responseHeaders.set(key, value);
    }
  });

  // Inject KeyVault telemetry metadata headers
  responseHeaders.set('X-KeyVault-Gateway', 'true');
  responseHeaders.set('X-KeyVault-Latency', `${latencyMs}ms`);
  responseHeaders.set('X-KeyVault-Service', serviceId);
  responseHeaders.set('X-KeyVault-Target-Url', targetUrl);
  if (rateLimitRemaining) responseHeaders.set('X-KeyVault-Upstream-Remaining', rateLimitRemaining);

  return new NextResponse(responseBody, {
    status: upstreamRes.status,
    headers: responseHeaders,
  });
}

export async function GET(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function POST(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function PUT(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function PATCH(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function DELETE(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function HEAD(req: NextRequest, context: { params: Promise<{ serviceId: string; path?: string[] }> }) {
  const { serviceId, path } = await context.params;
  return handleProxyRequest(req, serviceId, path);
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Requested-With',
    },
  });
}
